services:
  db:
    image: postgres
    volumes:
      - $HOME/srv/postgres:/var/lib/postgresql/data
      - ./Dupoly-Maven/database:/database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=lil-postgres
    expose:
      - 5432:5432
    ports:
      - 5432:5432
    restart: always
  # app:
  #   build: .
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_PASSWORD=password
  #   depends_on:
  #     - db