services:
  db:
    image: postgres
    volumes:
      - $HOME/srv/postgres:/var/lib/postgresql/data
      - ./database:/database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=lil-postgres
    expose:
      - 5432:5432
    ports:
      - 5432:5432
    restart: always
  # this has not been started yet, need jdbc Dockerfile to build !!!
  # app:
  #   build: .
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_USER=lil-postgres
  #   expose:
  #     - 8080:8080
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db

  #  psql -h localhost -U postgres -d test -f database/create.sh 